files:
  centroids: LLSOA_Dec_2021_PWC_for_England_and_Wales_2022_-7534040603619445107.geojson
  boundaries: Countries_December_2021_UK_BGC_2022_3072220700897643058.geojson
  output: distance_to_sea.csv
fields:
  output_field_name: "Distance to Sea (km)"
  area_code: LSOA21CD
